@startuml
'https://plantuml.com/class-diagram

class App{
    - File fileInput;
    - File fileOutput;
    - FileWriter fileWriter;
    - Scanner sc;
    - ArrayList<String[]> data;
    + {static} String[] splitNames(String names)
}

@enduml